services:
  mysql:
    image: mysql:8.3
    container_name: mysql-taskmanager

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-taskmanager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: