### Créer un nouvel utilisateur
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "JohnDoe"
}

### Récupérer un utilisateur par son ID
GET http://localhost:8080/api/users/1

### Récupérer les projets d'un utilisateur par son ID
GET http://localhost:8080/api/users/1/projects

### Récupérer les tâches d'un utilisateur par son ID
GET http://localhost:8080/api/users/1/tasks

### Créer un nouveau projet
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": "Course de la semaine",
  "creator": {
    "id": 1
  }
}

### Récupérer les tâches d'un projet par son ID
GET http://localhost:8080/api/projects/5

### Récupérer les tâches avec leurs détails d'un projet par son ID
GET http://localhost:8080/api/projects/1/tasks

### Créer une nouvelle tâche
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "tâche 4",
  "status": 0,
  "project": {
    "id": 5
  },
  "assignee": {
    "id": 1
  }
}

### Modifier le status une tâche existante
PATCH http://localhost:8080/api/tasks/1
Content-Type: application/json

{
  "status": 1
}
